homework-24/cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path
from actors.views import create_actor, all_actors_list, actor_view, update_actor
from movie.views import FilmListView, FilmDetailView, FilmCreateView, FilmUpdateView, FilmDeleteView, get_film_actors


urlpatterns = [
    path('admin/', admin.site.urls),
    path('actors/', all_actors_list),
    path('actors/<int:pk>', actor_view),
    path('create_actor', create_actor),
    path('update_actor/<int:pk>', update_actor),
    path('films/', FilmListView.as_view()),
    path('films/<int:pk>', FilmDetailView.as_view()),
    path('create_film/', FilmCreateView.as_view()),
    path('update_film/<int:pk>', FilmUpdateView.as_view()),
    path('delete_film/<int:pk>', FilmDeleteView.as_view()),
    path('films/<int:pk>/actors', get_film_actors),
]

homework-24/cinema/actors/models.py
from django.db import models


class Actor(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    films = models.ManyToManyField(to='movie.Film', blank=True)

    def __str__(self):
        return f'Actor #{self.pk}: {self.name} {self.surname}'


class Director(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)

    def __str__(self):
        return f'Director #{self.pk}: {self.name} {self.surname}'

homework-24/cinema/movie/models.py
from django.db import models
from django.core.validators import MaxValueValidator


class Film(models.Model):
    title = models.CharField(max_length=50)
    rating = models.FloatField(default=0, validators=[MaxValueValidator(10)])
    duration = models.DurationField()
    director = models.ForeignKey(to='actors.Director', on_delete=models.CASCADE)
    actors = models.ManyToManyField(to='actors.Actor', blank=True)

    def __str__(self):
        return f'{self.title} - {self.rating}/10⭐'

homework-24/cinema/actors/forms.py
from django import forms
from .models import Actor


class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = ['name', 'surname', 'films']
        widgets = {
            'films': forms.CheckboxSelectMultiple
        }

homework-24/cinema/actors/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Actor
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .forms import ActorForm


def all_actors_list(request):
    all_actors = Actor.objects.all()
    data = {'actors': all_actors}
    return render(request, template_name='actors_list_view.html', context=data)


def actor_view(request, pk):
    actor = Actor.objects.get(pk=pk)
    data = {'actor': actor}
    return render(request, template_name='actor_detail_view.html', context=data)


def create_actor(request):
    if request.method == 'POST':
        form = ActorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/actors')
    else:
        form = ActorForm()
    return render(request, 'create_actor.html', {'form': form})


def update_actor(request, pk):
    actor = get_object_or_404(Actor, pk=pk)
    if request.method == 'POST':
        form = ActorForm(request.POST, instance=actor)
        if form.is_valid():
            form.save()
            return redirect('/actors')
    else:
        form = ActorForm(instance=actor)
    return render(request, 'update_actor.html', {'form': form})


class ActorListView(ListView):
    model = Actor
    template_name = 'actors_list_view.html'


class ActorDetailView(DetailView):
    model = Actor
    template_name = 'actor_detail_view.html'


class ActorCreateView(CreateView):
    model = Actor
    template_name = 'create_actor.html'
    fields = '__all__'
    success_url = '/actors'


class ActorUpdateView(UpdateView):
    model = Actor
    template_name = 'update_actor.html'
    fields = '__all__'
    success_url = '/actors'


class ActorDeleteView(DeleteView):
    model = Actor
    template_name = 'delete_actor.html'
    success_url = '/actors'

homework-24/cinema/movie/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Film


class FilmListView(ListView):
    model = Film
    template_name = 'all_films_view.html'


class FilmDetailView(DetailView):
    model = Film
    template_name = 'film_detail_view.html'


class FilmCreateView(CreateView):
    model = Film
    template_name = 'create_film.html'
    fields = '__all__'
    success_url = '/films'


class FilmUpdateView(UpdateView):
    model = Film
    template_name = 'update_film.html'
    fields = '__all__'
    success_url = '/films'


class FilmDeleteView(DeleteView):
    model = Film
    template_name = 'delete_film.html'
    success_url = '/films'


def get_film_actors(request, pk):
    film = Film.objects.get(pk=pk)
    actors = film.actors.all()
    data = {'actors': actors}
    return render(request, template_name='film_actors_view.html', context=data)

homework-24/cinema/actors/templates/actor_detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ actor.name }} {{ actor.surname }}</h1>
</body>
</html>

homework-24/cinema/actors/templates/actors_list_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ACTORS</title>
</head>
<body>
<h1>ALL ACTORS</h1>
{% for actor in actors %}
<h3><li>{{ actor.name }} {{ actor.surname }}</li></h3>
{% endfor %}
</body>
</html>

homework-24/cinema/actors/templates/create_actor.html
<!-- mymodel_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create My Model</title>
</head>
<body>
    <h1>Create My Model</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</body>
</html>

homework-24/cinema/actors/templates/delete_actor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DELETE ACTOR</title>
</head>
<body>
    <form method="post">
    {% csrf_token %}
    <p>Are you sure to delete? </p>
    <button type="submit" value="delete">Delete</button>
    </form>
</body>
</html>

homework-24/cinema/actors/templates/update_actor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UPDATE ACTOR</title>
</head>
<body>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
    </form>
</body>
</html>

homework-24/cinema/movie/templates/all_films_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ALL FILMS</title>
</head>
<body>
<h1>ALL FILMS</h1>
{% for film in film_list %}
<h3><li>{{ film }}</li></h3>
{% endfor %}
</body>
</html>

homework-24/cinema/movie/templates/create_film.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CREATE FILM</title>
</head>
<body>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
    </form>
</body>
</html>

homework-24/cinema/movie/templates/delete_film.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DELETE FILM</title>
</head>
<body>
    <form method="post">
    {% csrf_token %}
    <h3>Are you sure to delete?</h3>
    <button type="submit" value="delete">Delete</button>
    </form>
</body>
</html>

homework-24/cinema/movie/templates/film_actors_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for actor in actors %}
<h3><li>{{ actor }}</li></h3>
{% endfor %}
</body>
</html>

homework-24/cinema/movie/templates/film_detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DETAIL VIEW</title>
</head>
<body>
<h3><li>{{ object }}</li></h3>
</body>
</html>

homework-24/cinema/movie/templates/update_film.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UPDATE FILM</title>
</head>
<body>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    </form>
</body>
</html>